//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chuong_trinh_PT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoThongKe
    {
        public int BaoCaoID { get; set; }
        public string LoaiBaoCao { get; set; }
        public string NoiDungBaoCao { get; set; }
        public Nullable<System.DateTime> NgayBaoCao { get; set; }
    }
}
