//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chuong_trinh_PT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSanPham
    {
        public int ChiTietSanPhamID { get; set; }
        public Nullable<int> SanPhamID { get; set; }
        public string ManHinh { get; set; }
        public string HeDieuHanh { get; set; }
        public string CameraTruoc { get; set; }
        public string CameraSau { get; set; }
        public string Chip { get; set; }
        public string RAM { get; set; }
        public string BoNhoTrong { get; set; }
        public string Sim { get; set; }
        public string Pin { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
