//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chuong_trinh_PT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyDuLieuEntities : DbContext
    {
        public QuanLyDuLieuEntities()
            : base("name=QuanLyDuLieuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admins> admins { get; set; }
        public virtual DbSet<BaoCaoThongKe> BaoCaoThongKe { get; set; }
        public virtual DbSet<CaiDatHeThong> CaiDatHeThong { get; set; }
        public virtual DbSet<ChiTietSanPham> ChiTietSanPham { get; set; }
        public virtual DbSet<DanhMuc> DanhMuc { get; set; }
        public virtual DbSet<DonHang> DonHang { get; set; }
        public virtual DbSet<Hang> Hang { get; set; }
        public virtual DbSet<HinhAnh> HinhAnh { get; set; }
        public virtual DbSet<HoTroKhachHang> HoTroKhachHang { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMai { get; set; }
        public virtual DbSet<LichSuDonHang> LichSuDonHang { get; set; }
        public virtual DbSet<MangXaHoi> MangXaHoi { get; set; }
        public virtual DbSet<NoiDung> NoiDung { get; set; }
        public virtual DbSet<QuanTriHeThong> QuanTriHeThong { get; set; }
        public virtual DbSet<SanPham> SanPham { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }
        public virtual DbSet<TimKiem> TimKiem { get; set; }
        public virtual DbSet<ThanhToan> ThanhToan { get; set; }
    }
}
