//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chuong_trinh_PT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietSanPham = new HashSet<ChiTietSanPham>();
            this.HinhAnh1 = new HashSet<HinhAnh>();
            this.TimKiem = new HashSet<TimKiem>();
        }
    
        public int SanPhamID { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> Soluong { get; set; }
        public string MoTa { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<int> DanhMucID { get; set; }
        public Nullable<int> HangID { get; set; }
        public string HinhAnh { get; set; }
        public string KhuyenMai { get; set; }
        public Nullable<int> CanhBaoTonKho { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public Nullable<int> CanhCaoDuoi { get; set; }
        public Nullable<int> CanhCaoTren { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietSanPham> ChiTietSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnh> HinhAnh1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimKiem> TimKiem { get; set; }
    }
}
