//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chuong_trinh_PT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimKiem
    {
        public int TimKiemID { get; set; }
        public Nullable<int> SanPhamID { get; set; }
        public string TenSanPham { get; set; }
        public string MaSanPham { get; set; }
        public Nullable<int> DanhMucID { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<int> HangID { get; set; }
        public string CauHinh { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual Hang Hang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
